FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY prisma ./prisma/
COPY prisma.config.ts ./
COPY generated ./generated/

EXPOSE 3000

CMD sh -c "npx prisma generate && npm run dev"
