FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

# Não instalar aqui, deixar para o compose rodar
RUN npm install --omit=dev

COPY prisma ./prisma/
COPY prisma.config.ts ./

EXPOSE 3000

CMD sh -c "npm run dev"
