FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy prisma schema
COPY prisma ./prisma/

# Expose port
EXPOSE 3000

# Generate Prisma Client and start dev server
CMD sh -c "npx prisma generate && npm run dev"
